export const StatTypes: Record<string, string> = {
    "Accuracy": "Pitching",
    "Acrobatics": "Defense",
    "Agility": "Defense",
    "Aiming": "Batting",
    "Arm": "Defense",
    "Awareness": "Defense",
    "Composure": "Defense",
    "Contact": "Batting",
    "Control": "Pitching",
    "Cunning": "Batting",
    "Deception": "Pitching",
    "Defiance": "Pitching",
    "Determination": "Batting",
    "Dexterity": "Defense",
    "Discipline": "Batting",
    "Greed": "Baserunning",
    "Guts": "Pitching",
    "Insight": "Batting",
    "Intimidation": "Batting",
    "Intuition": "Pitching",
    "Lift": "Batting",
    "Luck": "Special",
    "Muscle": "Batting",
    "Patience": "Defense",
    "Performance": "Baserunning",
    "Persuasion": "Pitching",
    "Presence": "Pitching",
    "Priority": "Batting",
    "Reaction": "Defense",
    "Rotation": "Pitching",
    "Selflessness": "Batting",
    "Speed": "Baserunning",
    "Stamina": "Pitching",
    "Stealth": "Baserunning",
    "Stuff": "Pitching",
    "Velocity": "Pitching",
    "Vision": "Batting",
    "Wisdom": "Batting",
}

export const StatEmoji: Record<string, string> = Object.fromEntries(Object.entries(StatTypes).map(
    ([name, type]) => ([name, type === 'Pitching' ? '☄️' : type === 'Batting' ? '🏏' : type === 'Baserunning' ? '🏃' : type === 'Defense' ? '🛡️' : '🍀'])
));
